# Generated by Django 4.0.8 on 2022-12-30 01:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "The sale price cannot be negative."
                            )
                        ],
                    ),
                ),
                (
                    "operation_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Operation code related to the payment.",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of the sale."
                    ),
                ),
                (
                    "full_sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total price of the sale.",
                        max_digits=8,
                    ),
                ),
                (
                    "pending_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Pending payment of the sale.",
                        max_digits=8,
                    ),
                ),
                (
                    "point_of_sale",
                    models.ForeignKey(
                        help_text="Sale's point of sale.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.pointofsale",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sale price of the product.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "The sale price cannot be negative."
                            )
                        ],
                    ),
                ),
                (
                    "number_of_units",
                    models.PositiveSmallIntegerField(help_text="Number of units."),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        help_text="Related allocation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.allocation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Related product.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        help_text="Related sale.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
