# Generated by Django 4.0.8 on 2022-12-30 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0001_initial"),
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="user",
            field=models.ForeignKey(
                help_text="User that performs the sale.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.ForeignKey(
                help_text="Payment type.",
                on_delete=django.db.models.deletion.CASCADE,
                to="management.paymenttype",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sale",
            field=models.ForeignKey(
                help_text="Related sale.",
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.sale",
            ),
        ),
    ]
